"""
Memory blade — dev tool context file generator.

Reads architecture/decision/convention entries from memory and renders
them into the context files each AI coding tool reads:

    CLAUDE.md                        Claude Code
    .cursorrules                     Cursor
    .windsurfrules                   Windsurf
    AGENTS.md                        OpenAI Codex / Agents
    .github/copilot-instructions.md  GitHub Copilot
    .augment/guidelines.md           Augment Code

Call sync_context_files() after storing entries tagged with
"architecture", "decision", or "convention".
"""

from __future__ import annotations

from pathlib import Path

from jackknife.blades.memory.models import MemoryEntry
from jackknife.blades.memory.retriever import MemoryRetriever
from jackknife.core.logging import get_logger

log = get_logger(__name__)


def _render_entries(entries: list[MemoryEntry], title: str) -> str:
    """Format a list of memory entries as a markdown section."""
    if not entries:
        return f"## {title}\n\n_No entries yet._\n"
    lines = [f"## {title}\n"]
    by_type: dict[str, list[MemoryEntry]] = {}
    for e in entries:
        by_type.setdefault(e.entry_type, []).append(e)
    for etype, group in sorted(by_type.items()):
        lines.append(f"\n### {etype.capitalize()}\n")
        for entry in group:
            tag_str = ", ".join(f"`{t}`" for t in entry.tags) if entry.tags else ""
            lines.append(f"- {entry.content}")
            if tag_str:
                lines.append(f"  _{tag_str}_")
    return "\n".join(lines) + "\n"


def _build_claude_md(entries: list[MemoryEntry], project_name: str) -> str:
    return f"""# {project_name} — Claude Code Context

Auto-generated by `jackknife memory sync`. Do not edit manually.

{_render_entries(entries, "Project Memory")}

## Commands

```bash
# Store a memory entry
jackknife memory store "Your note here" --tag architecture

# Search memory
jackknife memory search "your query"

# Regenerate context files
jackknife memory sync
```
"""


def _build_cursorrules(entries: list[MemoryEntry], project_name: str) -> str:
    return f"""# {project_name} — Cursor Rules

Auto-generated by jackknife memory sync.

{_render_entries(entries, "Project Context")}
"""


def _build_windsurfrules(entries: list[MemoryEntry], project_name: str) -> str:
    return f"""# {project_name} — Windsurf Rules

Auto-generated by jackknife memory sync.

{_render_entries(entries, "Project Context")}
"""


def _build_agents_md(entries: list[MemoryEntry], project_name: str) -> str:
    return f"""# {project_name} — Agents Context

Auto-generated by jackknife memory sync.

{_render_entries(entries, "Project Memory")}

## Setup

```bash
poetry install --all-extras
poetry run jackknife memory sync
```
"""


def _build_copilot_instructions(entries: list[MemoryEntry], project_name: str) -> str:
    lines = [f"# {project_name}\n\nAuto-generated by jackknife.\n"]
    for entry in entries[:20]:  # Copilot prefers shorter context
        lines.append(f"- [{entry.entry_type}] {entry.content}")
    return "\n".join(lines) + "\n"


def _build_augment_guidelines(entries: list[MemoryEntry], project_name: str) -> str:
    return f"""# {project_name} — Augment Guidelines

Auto-generated by jackknife memory sync.

{_render_entries(entries, "Project Context")}
"""


_FILES: dict[str, tuple[str, ...]] = {
    "CLAUDE.md": (),
    ".cursorrules": (),
    ".windsurfrules": (),
    "AGENTS.md": (),
    ".github/copilot-instructions.md": (".github",),
    ".augment/guidelines.md": (".augment",),
}

_BUILDERS = {
    "CLAUDE.md": _build_claude_md,
    ".cursorrules": _build_cursorrules,
    ".windsurfrules": _build_windsurfrules,
    "AGENTS.md": _build_agents_md,
    ".github/copilot-instructions.md": _build_copilot_instructions,
    ".augment/guidelines.md": _build_augment_guidelines,
}


async def sync_context_files(
    retriever: MemoryRetriever,
    project_root: Path,
    project_name: str = "Project",
) -> list[str]:
    """
    Regenerate all dev tool context files from project memory.

    Returns a list of paths that were written.
    """
    entries = await retriever.get_context_entries()
    written: list[str] = []

    for rel_path, parent_dirs in _FILES.items():
        for parent in parent_dirs:
            (project_root / parent).mkdir(parents=True, exist_ok=True)

        builder = _BUILDERS[rel_path]
        content = builder(entries, project_name)
        dest = project_root / rel_path
        dest.write_text(content, encoding="utf-8")
        written.append(str(dest))
        log.info("context_file_written", path=rel_path)

    log.info("context_sync_complete", files=len(written), entries=len(entries))
    return written
